sparsity:
  mode: nxm
  choices: [[[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]], [[1, 4], [2, 4], [4, 4]]]
  greedy:
    eps_min: 0.0
    eps_max: 0.8
    num_milti_paths : 10
    num_kept_paths  : 5
    metrics: 'loss_flops'
    cand_pool_size : 1000
    metrics:
      alpha: 1.0
      beta: 0.0 # focus on loss only
    compression_ratio_contraint: 0.45
    proxy_dataset:
      image_per_classes: 1

  sampling:
    flop_based: False
    min_flops: 1.6
    max_flops: 4.6
    step_size: 0.4
    